"""add category table and update expense, user

Revision ID: 34f180500aa4
Revises: 7856103e439a
Create Date: 2026-04-19 16:49:10.306107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34f180500aa4'
down_revision: Union[str, Sequence[str], None] = '7856103e439a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('monthly_budget', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.add_column('expenses', sa.Column('category_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('expenses_user_id_fkey'), 'expenses', type_='foreignkey')
    op.create_foreign_key(None, 'expenses', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'expenses', 'categories', ['category_id'], ['id'], ondelete='CASCADE')
    op.drop_column('expenses', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.create_foreign_key(op.f('expenses_user_id_fkey'), 'expenses', 'users', ['user_id'], ['id'])
    op.drop_column('expenses', 'category_id')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
